### PR TITLE
268 docs gtfs tutorial

### LINKED ISSUE #268: docs: GTFS tutorial
**Description of the Feature to be Added**

QMD notebook tutorial, demonstrating how to use the GTFS module with open GTFS data.

### PR DESCRIPTION
**Pull request by r-leyshon**
## Description

Fixes #268 

## Motivation and Context

Tutorial for inspecting & filtering GTFS
I have also made a few changes to the index structure in order to have the site sub-indexes render the table listings correctly. 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

rendered locally with quarto

## Checklist:

- [X] My code follows the intended structure of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ethan-moss — COMMENTED** [review]
Thanks @r-leyshon for putting this together - it's a really great job! I love the tutorial hints and solutions too, it's a great way to pick up the package API! The content is great and covers all major aspects of the `MultiGtfsInstance` class.

I have a few thoughts, and was wondering what you think about these before merging?
1. I can see you've added a sub-listing structure to cater for multiple GTFS tutorials. I think this is a good idea, but I'm unsure whether or not there would be more than one GTFS tutorial. What do you think?
2. When explain GTFS, I think it's useful to add [this link](https://gtfs.org/schedule/). -it's a great resource for understanding GTFS. What do you think? If you agree, this is a tiny change and I'm happy to do it as I'm finalising the PR.
3. What do you think about adding in the HTML report functions?

Curious to get your thoughts, but on the whole I'm good to merge 👍  Really great job again, I enjoyed reading through the tutorial - it's going to be a brilliant template to reuse for the others!

**Comment by r-leyshon** [comment]
> Thanks @r-leyshon for putting this together - it's a really great job! I love the tutorial hints and solutions too, it's a great way to pick up the package API! The content is great and covers all major aspects of the `MultiGtfsInstance` class.
> 
> I have a few thoughts, and was wondering what you think about these before merging?
> 
> 1. I can see you've added a sub-listing structure to cater for multiple GTFS tutorials. I think this is a good idea, but I'm unsure whether or not there would be more than one GTFS tutorial. What do you think?
> 2. When explain GTFS, I think it's useful to add [this link](https://gtfs.org/schedule/). -it's a great resource for understanding GTFS. What do you think? If you agree, this is a tiny change and I'm happy to do it as I'm finalising the PR.
> 3. What do you think about adding in the HTML report functions?
> 
> Curious to get your thoughts, but on the whole I'm good to merge 👍 Really great job again, I enjoyed reading through the tutorial - it's going to be a brilliant template to reuse for the others!

Hi @ethan-moss , I'd agree with all those points in principle. 
1. I couldn't work out how the articles I would write would be navigable from the site index. I updated things so I could see how it would work, but in doing so may have shifted Chesterton's Fence. I probably just need to see what the original intention was and go with that - no hard opinions from me.
2. Yes to that, good idea.
3. I couldn't get html_report to work. It may have been the ZeroDivisionError that we already know about but I should confirm to be sure. But it's a shame as that was a really helpful functionality that I originally wanted to make the main outcome for the tutorial.

Are you happy to implement the suggestions?

**Comment by r-leyshon** [comment]
@ethan-moss I added in the summarise_routes/trips task we discussed yesterday. I revisited the problem with html_report not working for one of the instances. It is a [long standing issue](#74), specifically where the feed is missing a shape_id field in shapes.txt. This same issue is also causing the following message to be printed with the new GTFS file we included yesterday:
"KeyError. Feed was not cleaned.".

My thoughts are that trying to populate the required shape_ID field of the table (without reverse engineering the entire shapes.txt from available data) should be a good shout.

**Comment by ethan-moss** [comment]
> @ethan-moss I added in the summarise_routes/trips task we discussed yesterday. I revisited the problem with html_report not working for one of the instances. It is a [long standing issue](#74), specifically where the feed is missing a shape_id field in shapes.txt. This same issue is also causing the following message to be printed with the new GTFS file we included yesterday: "KeyError. Feed was not cleaned.".
> 
> My thoughts are that trying to populate the required shape_ID field of the table (without reverse engineering the entire shapes.txt from available data) should be a good shout.

OK great, thanks @r-leyshon! I'll take a look. For the `hmtl_report` side, i'm fairly sure this is fixed in the large GTFS PR we have waiting 👍

**Review by ethan-moss — APPROVED** [review]
All LGTM - thanks again for a brilliant addition to the docs! It's definitely going to be a great template to use for the others.

**Pull request merged**
